2025-10-03 17:16:36,328 : INFO : root : Loading config.
2025-10-03 17:16:36,332 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2025-10-03 17:16:36,333 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\bad76953a596b8c99f832e0e98026c3b.mpf_cache
2025-10-03 17:16:36,334 : WARNING : ConfigProcessor : Config file in cache changed: C:\Users\richa\ttp5\config\config_switches.yaml
2025-10-03 17:16:36,334 : INFO : ConfigProcessor : Loading config from file C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\mpfconfig.yaml.
2025-10-03 17:16:36,344 : INFO : ConfigProcessor : Loading config: C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\mpfconfig.yaml
2025-10-03 17:16:36,344 : INFO : ConfigProcessor : Loading config from file C:\Users\richa\ttp5\config\config.yaml.
2025-10-03 17:16:36,346 : INFO : ConfigProcessor : Loading config: C:\Users\richa\ttp5\config\config.yaml
2025-10-03 17:16:36,348 : INFO : ConfigProcessor : Loading config: C:\Users\richa\ttp5\config\config_ball_devices.yaml
2025-10-03 17:16:36,349 : INFO : ConfigProcessor : Loading config: C:\Users\richa\ttp5\config\config_coils.yaml
2025-10-03 17:16:36,350 : INFO : ConfigProcessor : Loading config: C:\Users\richa\ttp5\config\config_flippers.yaml
2025-10-03 17:16:36,353 : INFO : ConfigProcessor : Loading config: C:\Users\richa\ttp5\config\config_switches.yaml
2025-10-03 17:16:36,355 : INFO : ConfigProcessor : Config file cache created: C:\Users\richa\AppData\Local\Temp\bad76953a596b8c99f832e0e98026c3b.mpf_cache
2025-10-03 17:16:36,442 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\77a998d318c788df5647a1900cedfc56.mpf_cache
2025-10-03 17:16:36,443 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\9c8dea79ca4d15ee886340e992e8cb9d.mpf_cache
2025-10-03 17:16:36,444 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\8ddee2e87a4f178751335e99da00e9c4.mpf_cache
2025-10-03 17:16:36,445 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\16d594341c3fbe91b1b6d496c05a6fb0.mpf_cache
2025-10-03 17:16:36,446 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\9ea1b14cb2b1cce5e8bf981a1ff8cfc5.mpf_cache
2025-10-03 17:16:36,447 : INFO : Machine : Mission Pinball Framework Core Engine v0.57.0.dev39
2025-10-03 17:16:36,447 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'force_assets_load': False, 'jsonlogging': False, 'logfile': 'logs\\2025-10-03-17-16-36-mpf-DESKTOP-RK7BE5M.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2025-10-03 17:16:36,447 : INFO : Machine : MPF path: C:\Users\richa\mpfvirtual4\lib\site-packages\mpf
2025-10-03 17:16:36,447 : INFO : Machine : Machine path: C:\Users\richa\ttp5
2025-10-03 17:16:36,447 : INFO : Machine : Platform: win32
2025-10-03 17:16:36,447 : INFO : Machine : Python executable location: C:\Users\richa\mpfvirtual4\Scripts\python.exe
2025-10-03 17:16:36,447 : INFO : Machine : Python version: 3.9.13 (64-bit)
2025-10-03 17:16:36,449 : INFO : Machine : Initializing MPF...
2025-10-03 17:16:36,829 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2025-10-03 17:16:36,938 : INFO : EventManager : Event: ======'machine_var_master_volume'====== Args={'value': 0.5, 'prev_value': None, 'change': True}
2025-10-03 17:16:36,938 : INFO : EventManager : Event: ======'machine_var_player1_score'====== Args={'value': 28284, 'prev_value': None, 'change': True}
2025-10-03 17:16:36,938 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'Mission Pinball Framework v0.57.0.dev39', 'prev_value': None, 'change': True}
2025-10-03 17:16:36,938 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'Mission Pinball Framework v0.57.0.dev39, Config version:6, Show version: 6, BCP version:1.1', 'prev_value': None, 'change': True}
2025-10-03 17:16:36,938 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.9.13', 'prev_value': None, 'change': True}
2025-10-03 17:16:36,953 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-10-10.0.19045-SP0', 'prev_value': None, 'change': True}
2025-10-03 17:16:36,953 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'prev_value': None, 'change': True}
2025-10-03 17:16:36,954 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '10', 'prev_value': None, 'change': True}
2025-10-03 17:16:36,954 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '10.0.19045', 'prev_value': None, 'change': True}
2025-10-03 17:16:36,954 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'AMD64', 'prev_value': None, 'change': True}
2025-10-03 17:16:36,954 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2025-10-03 17:16:36,969 : INFO : EventManager : Event: ======'init_phase_2'====== Args={}
2025-10-03 17:16:36,969 : INFO : SwitchController : Found active switch: ('2', <Platform.SmartVirtual>) <switch.s_trough1>
2025-10-03 17:16:36,969 : INFO : SwitchController : Found active switch: ('3', <Platform.SmartVirtual>) <switch.s_trough2>
2025-10-03 17:16:36,969 : INFO : SwitchController : Found active switch: ('4', <Platform.SmartVirtual>) <switch.s_trough3>
2025-10-03 17:16:36,969 : INFO : SwitchController : Found active switch: ('5', <Platform.SmartVirtual>) <switch.s_trough4>
2025-10-03 17:16:36,969 : INFO : SwitchController : Found active switch: ('6', <Platform.SmartVirtual>) <switch.s_trough5>
2025-10-03 17:16:36,969 : INFO : SwitchController : Found active switch: ('7', <Platform.SmartVirtual>) <switch.s_trough6>
2025-10-03 17:16:36,972 : INFO : EventManager : Event: ======'bcp_connection_attempt'====== Args={'name': 'local_display', 'host': 'localhost', 'port': 5050}
2025-10-03 17:16:36,974 : INFO : BCPClientSocket : Connecting BCP to 'local_display' at localhost:5050...
2025-10-03 17:16:38,994 : INFO : BCPClientSocket : Connected BCP to 'local_display' localhost:5050
2025-10-03 17:16:38,995 : INFO : EventManager : Event: ======'bcp_clients_connected'====== Args={}
2025-10-03 17:16:39,271 : INFO : EventManager : Event: ======'machine_var_mc_version'====== Args={'value': 'MPF-MC v0.57.0.dev10', 'prev_value': None, 'change': True}
2025-10-03 17:16:39,272 : INFO : EventManager : Event: ======'machine_var_mc_extended_version'====== Args={'value': 'MPF-MC v0.57.0.dev10 (config_version=6, BCP v1.1,                      Requires MPF API compatibility v0.57.0.dev19 or newer)', 'prev_value': None, 'change': True}
2025-10-03 17:16:39,274 : INFO : ball_device.bd_trough : BCH: Initial count: 6
2025-10-03 17:16:39,326 : INFO : ball_device.bd_trough : State: idle
2025-10-03 17:16:39,326 : INFO : ball_device.bd_plunger : BCH: Initial count: 0
2025-10-03 17:16:39,326 : INFO : ball_device.bd_plunger : State: idle
2025-10-03 17:16:39,343 : INFO : EventManager : Event: ======'init_phase_3'====== Args={}
2025-10-03 17:16:39,347 : INFO : EventManager : Event: ======'init_phase_4'====== Args={}
2025-10-03 17:16:39,347 : INFO : BallController : Initial balls found: 6
2025-10-03 17:16:39,348 : ERROR : asyncio : Exception in callback EventManager._queue_task_done(<Task finishe...sling_left>')>)
handle: <Handle EventManager._queue_task_done(<Task finishe...sling_left>')>)>
Traceback (most recent call last):
  File "C:\Users\richa\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\events.py", line 791, in _queue_task_done
    future.result()
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\events.py", line 704, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\devices\switch.py", line 80, in _check_duplicate_switch_numbers
    raise AssertionError(
AssertionError: Duplicate switch number 17 for switch <switch.s_sling_left>
2025-10-03 17:16:39,364 : INFO : Machine : Starting the main run loop.
2025-10-03 17:16:39,369 : INFO : Machine : Shutting down...
2025-10-03 17:16:39,370 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2025-10-03 17:16:40,381 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\machine.py", line 788, in _run_loop
    raise self._exception['exception']
  File "C:\Users\richa\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\events.py", line 791, in _queue_task_done
    future.result()
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\events.py", line 704, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\devices\switch.py", line 80, in _check_duplicate_switch_numbers
    raise AssertionError(
AssertionError: Duplicate switch number 17 for switch <switch.s_sling_left>
2025-10-03 17:16:50,736 : ERROR : root : 
Traceback (most recent call last):
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\machine.py", line 788, in _run_loop
    raise self._exception['exception']
  File "C:\Users\richa\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\events.py", line 791, in _queue_task_done
    future.result()
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\events.py", line 704, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\devices\switch.py", line 80, in _check_duplicate_switch_numbers
    raise AssertionError(
AssertionError: Duplicate switch number 17 for switch <switch.s_sling_left>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\commands\game.py", line 236, in __init__
    self.machine.run()
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\machine.py", line 684, in run
    self._run_loop()
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\machine.py", line 791, in _run_loop
    report_crash(self._exception['exception'], "exception_during_run", self.config)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\crash_reporter.py", line 236, in report_crash
    response = input("Do you want to report the crash to the MPF team (yes/no/show)? ")
EOFError
